#!/bin/bash

# Helper script for adding a Ubuntu PPA to a Debian system
# Only use this if you know the packages offered are compatible with your version of Debian,
# or you might break your system

arg=$@
ppaPath=${arg:4}
ppaName=${ppaPath%/*}

echo PPA : $arg
echo PPA Path : $ppaPath
echo PPA Name : $ppaName

sudo /usr/bin/add-apt-repository $@

read -e -p "Enter distribution name: " -i "utopic" name

echo "Before change"
cat /etc/apt/sources.list.d/*$ppaName*.list

sudo sed -i "s/jessie/$name/g" /etc/apt/sources.list.d/*$ppaName*.list

echo "After change"
cat /etc/apt/sources.list.d/*$ppaName*.list
