#!/bin/bash

# Applies replaygain info to all compatible files in the specified directory recursively
# (or to the specified file)

quiet=false
while getopts "q" opt; do
    case $opt in
        q)
            quiet=true
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 (-q) [file/directory]"
    exit
fi

if [[ ! -d "$1" && ! -f "$1" ]]; then
    echo "$1 not found"
    exit
fi

applyToFile () {
     # Convert filename to lowercase to match extension
     f="$1"
     filenameLower="${f,,}"

     if [[ $quiet == false ]]; then
         echo "Checking $f..."
     fi

     case "$filenameLower" in
         *.flac)
             metaflac --list "$f" | grep -q REPLAYGAIN

             # No replaygain data found
             if [[ $? -eq 1 ]]; then
                 echo "-> Applying replaygain to FLAC file $f"
                 metaflac --add-replay-gain "$f"

                 if [[ $? -eq 1 ]]; then
                     echo "Failed, trying to resample FLAC file $f"
                     ~/bin/resample_flac  "$f"
                 fi
             fi
             ;;

         *.ogg)
             vorbiscomment -l "$f"| grep -q REPLAYGAIN_TRACK

             # No replaygain data found
             if [[ $? -eq 1 ]]; then
                 echo "-> Applying replaygain to OGG file $f"
                 vorbisgain "$f"
             fi
             ;;

         *.mp3 | *.m4a )
             aacgain -s c "$f" | grep -q "Recommended"

             # No replaygain data found
             if [[ $? -eq 1 ]]; then
                 echo "-> Applying replaygain to MP3/M4A file $f"
                 aacgain -k "$f"
             fi
             ;;
    esac
}

if [[ -d "$1" ]]; then

    if [[ $quiet == false ]]; then
        echo "Applying to all files in $1"
    fi

    cd "$1"

    find . -type f | sort | while read f; do
        applyToFile "$f"
    done
else
    if [[ $quiet == false ]]; then
        echo "Applying to file $1"
    fi

    applyToFile "$1"
fi
