#!/bin/bash

# Convert files to MPEG, suitable for using in (my) car-radio

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 [file]"
    exit
fi

for file in "$@"
do
    echo "Converting $file"

    split_video "$file" 600

    find . -type f -name "${file%\.*}*-split-*" | while read splitFile; do
        splitFileMpeg=${splitFile%\.*}.mpeg
        echo "$splitFile -> $splitFileMpeg"

        if [[ $splitFile == *.mp3 ]]; then
            # Audio file
            echo "Audio file, converting to video file..."
            ffmpeg -nostdin -f lavfi -i 'color=c=black:s=720x480:r=24' -filter_complex "[0:v]drawtext=text='%{pts\:hms}':x=(w-tw)/2:y=h-(2*lh):fontcolor=white" -i "$splitFile" -map 0:v -map 1:a -target ntsc-dvd -threads 4 -aspect "16:9" -b:v 256k -shortest "$splitFileMpeg"
            ffmpegReturn=$?
        else
            # Video file
            ffmpeg -nostdin "$splitFile" -target ntsc-dvd -threads 4 -aspect "16:9" -b:v 256k "$splitFileMpeg"
            ffmpegReturn=$?
        fi

        if [[ $ffmpegReturn -ne 0 ]]; then
            echo "Error: ffmpeg did not return correctly"
            continue
        fi

        ls -lh "$splitFile"
        ls -lh "$splitFileMpeg"

        rm -vf "$splitFile"
    done

    rm -vf "$file"
done