#!/bin/bash

# Convert a file to MP4 using Handbrake

for convertFrom in "$@"
do
    convertTo=${convertFrom%\.*}.mp4
    echo "$convertFrom -> $convertTo"

    HandBrakeCLI -i "$convertFrom" -o "$convertTo" -e x264 --x264-preset slow -q 20 --crop 0:0:0:0 -loose-anamorphic

    ls -lh "$convertFrom"
    ls -lh "$convertTo"
done
