#!/bin/bash

# Change the screen configuration

echo "Dual Screen Changer"
echo "1- Enable external screen only"
echo "2- Enable both screens"
echo "3- Enable laptop screen only"
echo "0- Exit"
echo ""
read choice

if [[ $choice -eq 0 ]]; then
	echo "Aborted."
	exit
fi

echo "Sleeping. Make sure to switch to X if on a TTY."
sleep 5s

if [[ $choice -eq 1 ]]; then
    xrandr --output eDP-1 --off
    xrandr --output DP-2 --auto
    echo "Laptop screen disabled."
elif [[ $choice -eq 2 ]]; then
    xrandr --output eDP-1 --auto
    xrandr --output DP-2 --auto
    echo "Both screens enabled."
elif [[ $choice -eq 3 ]]; then
    xrandr --output eDP-1 --auto
    xrandr --output DP-2 --off
    echo "External screen disabled."
else
    exit
fi
