#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 [ISO file to mount/unmount]"
    exit
fi

isoFile="$1"
isoFileFullPath=$(readlink -f "$isoFile")

mount | grep -q "$isoFileFullPath"

if [[ $? -eq 0 ]]; then
    mountPoint=$(mount | grep "$isoFileFullPath" | cut -f 3 -d ' ')
    echo "ISO file $isoFile mounted on $mountPoint, unmounting..."
    sudo umount -v "$mountPoint"
    rmdir -v "$mountPoint"
else
    tempDirectory=$(mktemp -d -t tails-iso-XXXXXXXXXX)
    echo "Mounting $isoFileFullPath to $tempDirectory"
    sudo mount -v -o loop "$isoFileFullPath" "$tempDirectory"
fi
