#!/bin/bash

# Executes apply_replaygain on files in specified directory in parallel

quietOption=""
while getopts "q" opt; do
    case $opt in
        q)
            quietOption="-q"
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 [directory]"
    exit
fi

if [[ ! -d "$1" ]]; then
    echo "$1 not found"
    exit
fi

find "$1" -type f -print0 | xargs -0 --max-args=1 --max-procs=7 apply_replaygain ${quietOption}
