#!/bin/bash

# Start a VM with an ISO (or the current disc) to test that it is bootable and working correctly

if [[ $# -eq 1 ]]
then
	kvm -cdrom "$@" -boot d -m 512
else
	kvm -cdrom /dev/cdrom -boot d -m 512
fi
