#!/bin/bash

if [[ $# -eq 1 ]]
then
    echo "Argument, setting to $1"
    xinput --set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" $1
else
    current=`xinput --list-props "SynPS/2 Synaptics TouchPad" | grep Enabled | cut -f 3`
    echo "Current status: $current"

    if [[ $current -eq 0 ]]
    then
        echo "Disabled, enabling"
        xinput --set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 1
    else
        echo "Enabled, disabling"
        xinput --set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0
    fi
fi