#!/bin/bash

user=`whoami`

if [[ $user != "root" ]]; then
    sudo /home/tails/bin/update
    exit
fi

aptitude update
aptitude safe-upgrade
aptitude full-upgrade
apt-get autoclean
apt-get autoremove
apt-file update
